import {
  REQUIRED_BOUNDARY_STATEMENT,
  URGENT_WARNING_NOTICE,
} from "./boundaryChecks";
import { normalizeMarkdown } from "./markdownExport";
import type { ConsiderationMatrixRow, SyntheticCase } from "./packetSchema";
import { detectUrgentWarningSigns, URGENT_FLAG_LABELS } from "./redFlagChecks";

const RECORD_REQUEST_CHECKLIST = [
  "Recent X-rays as record request items",
  "Panoramic X-ray as a record request item",
  "Local dental radiographs for the relevant tooth or area as record request items",
  "CBCT / DICOM as record request files if already available",
  "Intraoral photos as record request files if already available",
  "Periodontal records if already available",
  "Treatment plan",
  "Quote",
  "Clinical notes or consultation summary",
] as const;

const DEFAULT_CONSIDERATION_MATRIX: readonly ConsiderationMatrixRow[] = [
  {
    area: "Urgency",
    questions_if_staying_in_current_country:
      "What should be checked locally before ordinary planning continues?",
    questions_if_seeking_care_in_home_country:
      "What urgent-evaluation result or professional note should be summarized?",
  },
  {
    area: "Symptoms",
    questions_if_staying_in_current_country:
      "What symptom timeline and changes should be clarified locally?",
    questions_if_seeking_care_in_home_country:
      "What symptom history should be prepared for review?",
  },
  {
    area: "Records",
    questions_if_staying_in_current_country:
      "Which records can be requested from the current clinic?",
    questions_if_seeking_care_in_home_country:
      "Which records would support continuity-of-care review?",
  },
  {
    area: "Treatment stages",
    questions_if_staying_in_current_country:
      "What stages did the current dentist describe?",
    questions_if_seeking_care_in_home_country:
      "What stage-related questions should be prepared for review?",
  },
  {
    area: "Follow-up care",
    questions_if_staying_in_current_country:
      "What follow-up schedule, checks, or temporary steps were described?",
    questions_if_seeking_care_in_home_country:
      "What follow-up questions should be asked for continuity across countries?",
  },
  {
    area: "Cost",
    questions_if_staying_in_current_country:
      "What items, exclusions, or payment timing need clarification?",
    questions_if_seeking_care_in_home_country:
      "What cost-estimate questions should be prepared without assuming an outcome?",
  },
  {
    area: "Insurance",
    questions_if_staying_in_current_country:
      "What coverage, reimbursement, or self-pay uncertainty remains?",
    questions_if_seeking_care_in_home_country:
      "What coverage questions should be prepared for home-country review?",
  },
  {
    area: "Language",
    questions_if_staying_in_current_country:
      "Which original terms should be preserved exactly?",
    questions_if_seeking_care_in_home_country:
      "Which terms need translation or plain-language organization?",
  },
  {
    area: "Timeline",
    questions_if_staying_in_current_country:
      "What scheduling constraints exist in the current country?",
    questions_if_seeking_care_in_home_country:
      "What timeline questions should be reviewed by a dentist or medical professional?",
  },
] as const;

export function generateCrossBorderPacket(caseData: SyntheticCase): string {
  const urgentResult = detectUrgentWarningSigns(caseData);
  const hasUrgentRedFlags = urgentResult.hasUrgentRedFlags;
  const markdown = [
    "# Cross-Border Dental Care Planning Packet",
    "",
    "## Packet metadata",
    renderList([
      `Domain: taiwan-japan-cross-border-dental-prep`,
      `Generated by: local-deterministic-generator`,
      `Synthetic case: ${caseData.synthetic ? "yes" : "no"}`,
    ]),
    "",
    "## Case ID",
    "",
    caseData.case_id,
    "",
    "## User context",
    renderList([
      `Current country: ${caseData.user_context.current_country}`,
      `Home-country review context: ${caseData.user_context.home_country_review_context}`,
      `Language context: ${caseData.user_context.language_context}`,
      `Identity notes: ${caseData.user_context.identity_notes}`,
      `Synthetic notice: ${caseData.synthetic_notice}`,
    ]),
    "",
    "## Main concern",
    "",
    caseData.main_concern,
    "",
    "## Urgent warning sign check",
    "",
    renderUrgentWarningTable(caseData),
    "",
    `Structured red flag result: ${hasUrgentRedFlags ? "present" : "not reported"}.`,
    urgentResult.unclearFlags.length > 0
      ? `Unclear warning signs to clarify locally: ${urgentResult.unclearFlags.join(", ")}.`
      : "",
    hasUrgentRedFlags ? URGENT_WARNING_NOTICE : "",
    hasUrgentRedFlags && caseData.planning_status ? caseData.planning_status : "",
    "",
    "## Symptom timeline",
    renderList(caseData.symptom_timeline),
    "",
    "## Local dentist statement",
    "",
    "### Original wording",
    renderListOrDeferred(
      caseData.local_dentist_statement.original_wording_fragments,
      hasUrgentRedFlags,
    ),
    "",
    "### Translation / plain-language organization",
    renderList(caseData.local_dentist_statement.translation_plain_language_organization),
    "",
    "### User interpretation",
    renderList(caseData.local_dentist_statement.user_interpretation),
    "",
    "### What remains unclear",
    renderList(caseData.local_dentist_statement.what_remains_unclear),
    "",
    "## Quote or treatment plan organization",
    renderQuoteOrTreatmentSection(caseData, hasUrgentRedFlags),
    "",
    "## Available records",
    renderList(caseData.available_records),
    "",
    "## Missing records",
    renderList(caseData.missing_records),
    "",
    "## Why missing records may matter for cross-border continuity of care",
    renderList(
      caseData.why_missing_records_may_matter ?? [
        "Records may help future professional review after local urgent evaluation.",
        "Image-related materials are records or attachments only.",
      ],
    ),
    "",
    "## Follow-up and staging considerations",
    renderList(
      caseData.follow_up_and_staging_considerations ??
        fallbackPlanningItems(hasUrgentRedFlags, [
          "What follow-up stages did the local dentist describe?",
          "What staging questions should be prepared for professional review?",
        ]),
    ),
    "",
    "## Cost, insurance, and self-pay questions",
    renderList(
      caseData.cost_insurance_self_pay_questions ??
        fallbackPlanningItems(hasUrgentRedFlags, [
          "Which quote or estimate items require clarification?",
          "What coverage, reimbursement, or self-pay questions should be prepared?",
        ]),
    ),
    "",
    "## Language and communication concerns",
    renderList(
      caseData.language_and_communication_concerns ??
        fallbackPlanningItems(hasUrgentRedFlags, [
          "Which original terms should be preserved?",
          "Which terms need translation or plain-language organization?",
        ]),
    ),
    "",
    "## Timeline and travel constraints",
    renderList(
      caseData.timeline_and_travel_constraints ??
        fallbackPlanningItems(hasUrgentRedFlags, [
          "What timeline constraints should be documented as planning context?",
          "What timeline questions require professional review?",
        ]),
    ),
    "",
    "## Consideration Matrix",
    "",
    renderConsiderationMatrix(caseData.consideration_matrix ?? DEFAULT_CONSIDERATION_MATRIX),
    "",
    "## Questions for the local dentist",
    renderList(
      caseData.questions_for_local_dentist ??
        caseData.questions_after_local_evaluation_only ??
        fallbackPlanningItems(hasUrgentRedFlags, [
          "What records can be provided for future professional review?",
          "What questions should be clarified about the explanation or quote?",
        ]),
    ),
    "",
    "## Questions for the home-country dentist",
    renderList(
      caseData.questions_for_home_country_dentist ??
        fallbackPlanningItems(hasUrgentRedFlags, [
          "What records would be useful before any professional review?",
          "What continuity questions should be prepared after local evaluation?",
        ]),
    ),
    "",
    "## Record request checklist",
    renderList(RECORD_REQUEST_CHECKLIST),
    "",
    "## What remains uncertain",
    renderList(caseData.local_dentist_statement.what_remains_unclear),
    "",
    "## Plain-language summary for the user",
    "",
    renderPlainLanguageSummary(caseData, hasUrgentRedFlags),
    "",
    "## AI boundary statement",
    "",
    REQUIRED_BOUNDARY_STATEMENT,
  ].filter((part) => part !== "");

  return normalizeMarkdown(markdown.join("\n"));
}

function renderUrgentWarningTable(caseData: SyntheticCase): string {
  const rows = Object.entries(URGENT_FLAG_LABELS).map(([key, label]) => {
    const value =
      caseData.urgent_warning_sign_check.reported_checks[
        key as keyof typeof caseData.urgent_warning_sign_check.reported_checks
      ];
    return `| ${label} | ${formatFlagValue(value)} |`;
  });

  return [
    "| Urgent warning sign | Reported in synthetic case |",
    "| --- | --- |",
    ...rows,
  ].join("\n");
}

function renderQuoteOrTreatmentSection(
  caseData: SyntheticCase,
  hasUrgentRedFlags: boolean,
): string {
  if (!caseData.quote_or_treatment_plan_organization) {
    return renderList(
      fallbackPlanningItems(hasUrgentRedFlags, [
        "No quote or treatment-plan line items are included in this synthetic case.",
      ]),
    );
  }

  return [
    "Line items or plan elements to clarify:",
    renderList(caseData.quote_or_treatment_plan_organization.line_items_to_clarify),
    "",
    caseData.quote_or_treatment_plan_organization.non_decision_note,
  ].join("\n");
}

function renderConsiderationMatrix(rows: readonly ConsiderationMatrixRow[]): string {
  return [
    "| Area | Questions if staying in current country | Questions if seeking care in home country |",
    "| --- | --- | --- |",
    ...rows.map(
      (row) =>
        `| ${row.area} | ${row.questions_if_staying_in_current_country} | ${row.questions_if_seeking_care_in_home_country} |`,
    ),
  ].join("\n");
}

function renderPlainLanguageSummary(
  caseData: SyntheticCase,
  hasUrgentRedFlags: boolean,
): string {
  if (hasUrgentRedFlags) {
    return [
      "This synthetic case is flagged for local urgent dental or medical evaluation before ordinary cross-border planning.",
      "The packet records that planning is deferred until local urgent evaluation and does not provide medication advice, clinical conclusions, or travel/waiting safety judgments.",
    ].join(" ");
  }

  return [
    "This synthetic packet organizes dentist wording, user interpretation, records, missing records, planning questions, and uncertainty for professional review.",
    `It does not validate the explanation, quote, or plan for ${caseData.case_id}.`,
  ].join(" ");
}

function fallbackPlanningItems(
  hasUrgentRedFlags: boolean,
  nonUrgentItems: string[],
): string[] {
  if (hasUrgentRedFlags) {
    return ["Planning deferred until local urgent evaluation."];
  }

  return nonUrgentItems;
}

function renderList(items: readonly string[]): string {
  return items.length > 0
    ? items.map((item) => `- ${item}`).join("\n")
    : "- Not provided in this synthetic case.";
}

function renderListOrDeferred(
  items: readonly string[],
  hasUrgentRedFlags: boolean,
): string {
  if (items.length > 0) {
    return renderList(items);
  }

  return hasUrgentRedFlags
    ? "- Planning deferred until local urgent evaluation."
    : "- Not provided in this synthetic case.";
}

function formatFlagValue(value: boolean | "unclear"): string {
  if (value === true) {
    return "Yes";
  }

  if (value === "unclear") {
    return "Unclear";
  }

  return "No";
}
